#########################################################
## Elasticsearch Service
#########################################################
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch01
spec:
  ports:
    - name: elasticsearch-http
      port: @elastic.port.container@
      protocol: TCP
      targetPort: @elastic.port.container@
  selector:
    app: elasticsearch01

#########################################################
## Elasticsearch Deployment
#########################################################
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch01
  template:
    metadata:
      labels:
        app: elasticsearch01
    spec:
      containers:
        - name: es01
          image: docker.io/library/elasticsearch:@elk.version@
          env:
            - name: discovery.type
              value: single-node
            - name: ELASTIC_PASSWORD
              value: ${ELASTIC_ADMIN_PASSWORD}
            - name: xpack.security.enabled
              value: "true"
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: elasticsearch-data-dir
      initContainers:
        - name: es01-init
          image: docker.io/library/elasticsearch:@elk.version@
          command:
            - init-elasticsearch.sh
          env:
            - name: discovery.type
              value: single-node
            - name: ELASTIC_PASSWORD
              value: ${ELASTIC_ADMIN_PASSWORD}
            - name: xpack.security.enabled
              value: "true"
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: elasticsearch-data-dir
            - mountPath: /usr/local/bin/init-elasticsearch.sh
              name: elasticsearch-init-script
      volumes:
        - name: elasticsearch-data-dir
          hostPath:
            path: "@install.dir@/elasticsearch/data"
            type: Directory
        - name: elasticsearch-init-script
          hostPath:
            path: "@install.dir@/elasticsearch/init-scripts/init-elasticsearch.sh"
            type: File
