#########################################################
## Kibana Service
#########################################################
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
spec:
  ports:
    - name: kibana-http
      port: @kibana.port.container@
      protocol: TCP
      targetPort: @kibana.port.container@
  selector:
    app: kibana

#########################################################
## Kibana Deployment
#########################################################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana1
          image: docker.io/library/kibana:@elk.version@
          env:
            - name: SERVERNAME
              value: kibana
            - name: ELASTICSEARCH_HOSTS
              value: http://elasticsearch01-pod:@elastic.port.container@
            - name: ELASTICSEARCH_USERNAME
              value: ${KIBANA_SYSTEM_USER}
            - name: ELASTICSEARCH_PASSWORD
              value: ${KIBANA_SYSTEM_PASSWORD}
