#########################################################
## MongoDB Service
#########################################################
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  ports:
    - name: mongodb-tcp
      port: @mongo.port.container@
      protocol: TCP
      targetPort: @mongo.port.container@
  selector:
    app: mongodb

#########################################################
## MongoDB Deployment
#########################################################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
        stackId: data
        traefik.enable: true
        traefik.tcp.routers.mongodb-router.entrypoints: mongo-tcp
        traefik.tcp.routers.mongodb-router.rule: HostSNI(`localhost`)
        traefik.tcp.routers.mongodb-router.service: mongodb
        traefik.tcp.routers.mongodb-router.tls: true
        traefik.tcp.routers.mongodb-router.tls.options: default
        traefik.tcp.services.mongodb.loadbalancer.server.port: @mongo.port.container@
    spec:
      containers:
        - name: mongodb
          image: docker.io/library/mongo:@mongo.version@
          args:
            - --quiet
            - --keyFile
            - /data/db/rs-keys/rs-key
            - --replSet
            - @mongo.replica-set.name@
            - --bind_ip_all
            - --auth
            - --enableFreeMonitoring
            - off
            - --journal
          volumeMounts:
            - mountPath: /data/db
              name: mongodb-data-dir
            - mountPath: /data/configdb
              name: mongodb-data-configdb-dir
          livenessProbe:
            exec:
              command:
                - mongosh
                - --quiet
                - --eval
                - "db.runCommand('ping').ok"
            initialDelaySeconds: 5
            periodSeconds: 5
      initContainers:
        - name: 01-mongodb-init
          image: docker.io/library/mongo:@mongo.version@
          command:
            - init-entrypoint-wrapper.sh
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: @mongo.root-user.name@
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: ${MONGO_SUPERUSER_PASSWORD}
            - name: MONGO_INITDB_DATABASE
              value: admin
          volumeMounts:
            - mountPath: /data/db
              name: mongodb-data-dir
            - mountPath: /data/configdb
              name: mongodb-data-configdb-dir
            - mountPath: /docker-entrypoint-initdb.d
              name: mongodb-initdb-dir
            - mountPath: /usr/local/bin/init-entrypoint-wrapper.sh
              name: mongodb-entrypoint-wrapper
        - name: 02-mongodb-rs-init
          image: docker.io/library/mongo:@mongo.version@
          command:
            - init-replica-set.sh
          args:
            - --fork
            - --logpath
            - "/dev/stdout"
            - --keyFile
            - /data/db/rs-keys/rs-key
            - --replSet
            - @mongo.replica-set.name@
            - --auth
            - --journal
          volumeMounts:
            - mountPath: /data/db
              name: mongodb-data-dir
            - mountPath: /data/configdb
              name: mongodb-data-configdb-dir
            - mountPath: /usr/local/bin/init-replica-set.sh
              name: mongodb-init-replica-set
      volumes:
        - name: mongodb-data-dir
          hostPath:
            path: "@install.dir@/mongodb/db"
            type: Directory
        - name: mongodb-data-configdb-dir
          hostPath:
            path: "@install.dir@/mongodb/configdb"
            type: Directory
        - name: mongodb-initdb-dir
          hostPath:
            path: "@install.dir@/mongodb/init-scripts"
            type: Directory
        - name: mongodb-entrypoint-wrapper
          hostPath:
            path: "@install.dir@/mongodb/util-scripts/init-entrypoint-wrapper.sh"
            type: File
        - name: mongodb-init-replica-set
          hostPath:
            path: "@install.dir@/mongodb/util-scripts/init-replica-set.sh"
            type: File
