#########################################################
## Traefik Service
#########################################################
---
apiVersion: v1
kind: Service
metadata:
  name: traefik
spec:
  ports:
    - name: dashboard-port
      port: @data-dashboard.port@
      protocol: TCP
      targetPort: @data-dashboard.port@
    - name: mongo-port
      port: @mongo.port.host@
      protocol: TCP
      targetPort: @mongo.port.host@
    - name: elastic-port
      port: @elastic.port.host@
      protocol: TCP
      targetPort: @elastic.port.host@
    - name: kibana-port
      port: @kibana.port.host@
      protocol: TCP
      targetPort: @kibana.port.host@
    - name: vault-port
      port: @vault.port.host@
      protocol: TCP
      targetPort: @vault.port.host@
  selector:
    app: traefik

#########################################################
## Traefik Deployment
#########################################################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
        stackId: data
        traefik.enable: true
        traefik.http.routers.dashboard.entrypoints: websecure
        traefik.http.routers.dashboard.rule: HostRegexp(`data.{name:.+}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
        traefik.http.routers.dashboard.tls: true
        traefik.http.routers.dashboard.tls.options: default
        traefik.http.routers.dashboard.service: api@internal
        traefik.http.routers.dashboard.middlewares: dashboard-auth
        traefik.http.middlewares.dashboard-auth.basicauth.usersfile: /etc/credentials.txt
    spec:
      containers:
        - name: proxy
          image: docker.io/traefik:@traefik.version@
          args:
            - --global.checkNewVersion=false
            - --global.sendAnonymousUsage=false
            - --accessLog=true
            - --accessLog.format=json
            - --api=true
            - --api.dashboard=true
            - --entrypoints.websecure.address=:@data-dashboard.port@
            - --entrypoints.mongo-tcp.address=:@mongo.port.host@
            - --entrypoints.elasticsearch-http.address=:@elastic.port.host@
            - --entrypoints.kibana-http.address=:@kibana.port.host@
            - --entrypoints.vault-http.address=:@vault.port.host@
            - --providers.docker=true
            - --providers.docker.exposedbydefault=false
            - --providers.docker.network=data_network
            - --providers.docker.constraints=Label(`stackId`,`data`)
            - --providers.file.directory=/etc/traefik/dynamic
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: podman-sock-file
            - mountPath: /etc/traefik/dynamic
              name: traefik-dynamic-config-dir
            - mountPath: /etc/credentials.txt
              name: traefik-dashboard-basic-auth-file
            - mountPath: /certs/test.crt
              name: test-cert-file
            - mountPath: /certs/test.key
              name: test-key-file
            - mountPath: /certs/trust.pem
              name: trust-pem-file
          ports:
            - containerPort: @data-dashboard.port@
              hostPort: @data-dashboard.port@
            - containerPort: @mongo.port.container@
              hostPort: @mongo.port.host@
            - containerPort: @elastic.port.container@
              hostPort: @elastic.port.host@
            - containerPort: @kibana.port.container@
              hostPort: @kibana.port.host@
            - containerPort: @vault.port.container@
              hostPort: @vault.port.host@
      volumes:
        - name: podman-sock-file
          hostPath:
            path: ${XDG_RUNTIME_DIR}/podman/podman.sock
            type: File
        - name: traefik-dynamic-config-dir
          hostPath:
            path: "@install.dir@/traefik/config"
            type: Directory
        - name: traefik-dashboard-basic-auth-file
          hostPath:
            path: "@install.dir@/traefik/credentials.txt"
            type: File
        - name: test-cert-file
          hostPath:
            path: "@install.dir@/certs/test.crt"
            type: File
        - name: test-key-file
          hostPath:
            path: "@install.dir@/certs/test.key"
            type: File
        - name: trust-pem-file
          hostPath:
            path: "@install.dir@/certs/myCA.pem"
            type: File
