#########################################################
## HashiCorp Vault Service
#########################################################
---
apiVersion: v1
kind: Service
metadata:
  name: vault
spec:
  ports:
    - name: vault-tcp
      port: @vault.port.container@
      protocol: TCP
      targetPort: @vault.port.container@
  selector:
    app: vault

#########################################################
## HashiCorp Vault Deployment
#########################################################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
        stackId: data
        traefik.enable: true
        traefik.http.routers.vault-router.entrypoints: vault-http
        traefik.http.routers.vault-router.rule: HostRegexp(`{name:.+}`)
        traefik.http.routers.vault-router.service: vault
        traefik.http.routers.vault-router.tls: true
        traefik.http.routers.vault-router.tls.options: default
        traefik.http.services.vault.loadbalancer.server.port: @vault.port.container@
    spec:
      containers:
        - name: vault
          image: docker.io/hashicorp/vault:@vault.version@
          env:
            - name: VAULT_DEV_ROOT_TOKEN_ID
              value: ${VAULT_DEV_ROOT_TOKEN_ID}
            - name: VAULT_ADDR
              value: http://127.0.0.1:@vault.port.container@
            - name: VAULT_TOKEN
              value: ${VAULT_DEV_ROOT_TOKEN}
            - name: MONGODB_URL
              value: mongodb-pod:@mongo.port.container@
          volumeMounts:
            - mountPath: /vault/logs
              name: vault-logs-dir
            - mountPath: /vault/file
              name: vault-file-dir
      volumes:
        - name: vault-logs-dir
          hostPath:
            path: "@install.dir@/vault/logs"
            type: Directory
        - name: vault-file-dir
          hostPath:
            path: "@install.dir@/vault/file"
            type: Directory
