#########################################################
## HashiCorp Vault Service
#########################################################
---
apiVersion: v1
kind: Service
metadata:
  name: vault
spec:
  ports:
    - name: vault-tcp
      port: 8200
      protocol: TCP
      targetPort: 8200
  selector:
    app: vault

#########################################################
## HashiCorp Vault Deployment
#########################################################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
        stackId: data
        traefik.enable: true
        traefik.http.routers.vault-router.entrypoints: vault-http
        traefik.http.routers.vault-router.rule: HostRegexp(`{name:.+}`)
        traefik.http.routers.vault-router.service: vault
        traefik.http.routers.vault-router.tls: true
        traefik.http.routers.vault-router.tls.options: default
        traefik.http.services.vault.loadbalancer.server.port: 8200
    spec:
      containers:
        - name: vault
          image: docker.io/hashicorp/vault:1.13.1
          env:
            - name: VAULT_DEV_ROOT_TOKEN_ID
              value: root
            - name: VAULT_ADDR
              value: http://127.0.0.1:8200
            - name: VAULT_TOKEN
              value: root
            - name: MONGODB_URL
              value: mongodb-pod:27017
          volumeMounts:
            - mountPath: /vault/logs
              name: vault-logs-dir
            - mountPath: /vault/file
              name: vault-file-dir
      volumes:
        - name: vault-logs-dir
          hostPath:
            path: "/tmp/vault-demo/vault/logs"
            type: Directory
        - name: vault-file-dir
          hostPath:
            path: "/tmp/vault-demo/vault/file"
            type: Directory
